version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=default
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pw
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
  server:
    image: marctv/minecraft-papermc-server:latest
    ports:
      - 25565:25565
      - 5005:5005
    environment:
      - JAVAFLAGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
      - ./server:/data
      - ./plg:/data/plugins