version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - 5432:5432
  server:
    image: marctv/minecraft-papermc-server:latest
    ports:
      - 25565:25565
    volumes:
      - ./server:/data