version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - 5432:5432
  server:
    image: marctv/minecraft-papermc-server:latest
    ports:
      - 25565:25565
      - 5005:5005
    environment:
      - JAVAFLAGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
      - ./server:/data