database:
  user: user
  password: pw
  name: default
  url: jdbc:mysql://mysql/
i18n:
  languages:
    de:
      errorCreateGroup: "§cEs ist ein Fehler beim Erstellen der Gruppe aufgetreten. Stelle sicher, dass die Gruppen-ID einzigartig ist."
      successCreateGroup: "§aGruppe erstellt."
      errorUpdateGroup: "§cEs ist ein Fehler beim Modifizieren der Gruppe aufgetreten. Stelle sicher, dass die Gruppen-ID existiert."
      successUpdateGroup: "§aGruppe angepasst."
      errorDeleteGroup: "§cEs ist ein Fehler beim Löschen der Gruppe aufgetreten. Stelle sicher, dass die Gruppen-ID existiert."
      successDeleteGroup: "§aGruppe gelöscht."
      errorDefaultGroup: "§cEs ist ein Fehler beim Setzen der Standard-Gruppe aufgetreten. Stelle sicher, dass die Gruppen-ID existiert."
      successDefaultGroup: "§aStandard Gruppe gesetzt."
      errorPlayerGroup: "§cEs ist ein Fehler beim zuweisen der Gruppe aufgetreten. Stelle sicher, dass der Spieler und die Gruppe existiert."
      successPlayerGroup: "§aSpieler-Gruppe gesetzt."
      noSuchPlayer: "§cSpieler nicht gefunden."
      noSuchGroup: "§cGruppe nicht gefunden"
      invalidDuration: "§cBeachten Sie die Formatierung der Dauer: TT:HH:MM:SS"
      durationTooLong: "§cDie Dauer ist zu lange."
      successRemovePlayerGroup: "§aSpieler-Gruppe entfernt."
      errorRemovePlayerGroup: "§cFehler beim Entfernen der Spieler-Gruppe."
      playerJoin: "ist dem Spiel beigetreten"
      successSignCreate: "§aRang-Schild erstellt."
      errorSignCreate: "§cRang-Schild konnte nicht erstellt werden. Eventuell existiert an ihrer Position kein Schild."
      successGroupPermissions: "§aBerechtigungen angepasst."
      errorGroupPermissions: "§cFehler beim Anpassen der Berechtigungen."
    en:
      errorCreateGroup: "§cThere was an error creating the group. Make sure the group ID is unique."
      successCreateGroup: "§aGroup created."
      errorUpdateGroup: "§cThere was an error updating the group. Make sure a group with the provided ID exists."
      successUpdateGroup: "§aGroup updated."
      errorDeleteGroup: "§cThere was an error deleting the group. Make sure a group with the provided ID exists."
      successDeleteGroup: "§aGroup deleted."
      errorDefaultGroup: "§cThere was an error setting the default group. Make sure a group with the provided ID exists."
      successDefaultGroup: "§aDefault group set."
      errorPlayerGroup: "§cThere was an error setting the player group. Make sure the group and player exists."
      successPlayerGroup: "§aPlayer group set."
      noSuchPlayer: "§cPlayer not found"
      noSuchGroup: "§cGroup not found"
      invalidDuration: "§cPlease play attention to the formatting of the duration: DD:HH:MM:SS"
      durationTooLong: "§cDuration is too long."
      successRemovePlayerGroup: "§aPlayer group removed."
      errorRemovePlayerGroup: "§cError removing player group."
      playerJoin: "Joined the game"
      successSignCreate: "§aRank sign created."
      errorSignCreate: "§cRank sign could not be created. Make sure you are standing on a sign."
      successGroupPermissions: "§aPermissions adjusted."
      errorGroupPermissions: "§cAn error occurred while adjusting the permissions."

  defaultLanguage: de